language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
services:
  - docker
before_install:
  # docker build -t <Dockerイメージ名> <Dockerfileが存在するディレクトリ>
  - docker build -t edar_reacrt_test .
  - docker ps -a
  - docker run edar_reacrt_test /bin/bash -c "yarn test"
install:
  # - npm install -g firebase-tools
  - yarn install

script:
  - yarn test
