language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - npm run build || true
  - npm test
# deploy:
#   provider: pages
#   skip_cleanup: true
#   on:
#     branch: master
