# ステージ: 上から順に実行し、成功すると次のステージに進む
stages:
  # 文法チェック
  - name: syntax
  # テストコードの実行
  - name: test
  # firebaseへのデプロイ処理
  - name: deploy
services:
  - docker
# docker imageのビルド処理
_build_docker: &build_docker
  before_script:
    - docker build -t edar_react_test .
_test_in_docker: &test_in_docker

jobs:
  include:
    - stage: syntax
      name: syntax check
      <<: *build_docker
      script:
        - docker run -it -e CI=true --entrypoint=bash edar_react_test -c "yarn eslint . --ext .tsx --ext .ts"
    - stage: test
      name: react test
      <<: *build_docker
      script:
        - docker run -it -e CI=true --entrypoint=bash edar_react_test -c "yarn test"
    - stage: deploy
      name: deploy firebase
      <<: *build_docker
      # masterブランチにマージされたときに実行する
      if: branch = master
      script:
        - echo "deploy firebase"
