stages:
  - name: syntax
  - name: test
  - name: deploy
    if: branch IN (master) AND type = 'push'
services:
  - docker

_build_docker: &build_docker
  before_script:
    - docker build -t edar_react_test .
_test_in_docker: &test_in_docker

jobs:
  include:
    - <<: *build_docker
    - stage: syntax
      name: syntax check
      script:
        - docker run -it -e CI=true --entrypoint=bash edar_react_test -c "yarn test"
    - stage: test
      name: react test
      script:
        - docker run -it -e CI=true --entrypoint=bash edar_react_test -c "yarn eslint . --ext .tsx --ext .ts"
    - stage: deploy
      name: deploy firebase
      script:
        - echo "deploy firebase"
