language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules

install:
  # - npm install -g firebase-tools
  - yarn install

script:
  - yarn test
# deploy:
#   provider: pages
#   skip_cleanup: true
#   on:
#     branch: master
