FROM node:12.16.1-alpine

ARG FIREBASE_PROJECT_ID
# コンテナ内で作業するディレクトリを指定
WORKDIR /usr/src/edar

# ローカルファイルを全部作業用ディレクトリにコピー
COPY ./src/edar .
# パッケージのインストール

RUN yarn add firebase-tools & sed -i -e "s/__firebase_project__/${FIREBASE_PROJECT_ID}/" .firebaserc
RUN yarn install
RUN ls node_modules/
RUN cat package.json
RUN cat yarn.lock
# コンテナを起動する際に実行されるコマンド
ENTRYPOINT [ "yarn", "start"]
