version: "3"
services:
  react:
    build:
      context: .
    volumes:
      - ./src/edar/:/usr/src/edar/
      - ./src/edar/src:/usr/src/edar/src
    ports:
      - 3000:3000
    entrypoint: >
      sleep 86400
