name: Test CI

on: push

jobs:
  lint: #ジョブ名
    runs-on: ubuntu-latest #実行環境(Ubuntuの最新版環境で実行)
    env:
      DOCKER_IMAGE_NAME: edar_react_test
      DEPLOY_DOCKER_IMAGE_NAME: edar_deploy
    steps: #実行処理やコマンドを記述
      - name: git checkout current branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: create docker image
        run: docker build -t $DOCKER_IMAGE_NAME .
      - name: run docker container
        run: docker run -t --entrypoint=bash $DOCKER_IMAGE_NAME -c "yarn eslint . --ext .tsx --ext .ts"
  test:
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - name: git checkout current branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: create docker image
        run: docker build -t samle_image_name -f ./Dockerfile .
      - name: run docker container test
        run: docker run -t samle_image_name bin/sh -c "echo myproject deploy"
  deploy:
    # if: contains( github.ref, 'master')
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - name: git checkout current branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: create docker image
        run: docker build -t samle_image_name -f ./Dockerfile .
      - name: run docker container deploy
        run: docker run -t samle_image_name bin/sh -c "echo hogehoge deploy"
