name: EDAR CI CD 

on: push

env: # global環境変数を設定
  DOCKER_IMAGE_NAME: edar_react_test
  # DOCKER_FILE_NAME:
  DEPLOY_DOCKER_IMAGE_NAME: edar_deploy
  SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
  REACT_APP_RSTRNT_API_USER: ${{ secrets.REACT_APP_RSTRNT_API_USER }}
  REACT_APP_RSTRNT_API_PASSWORD: ${{ secrets.REACT_APP_RSTRNT_API_PASSWORD }}
  REACT_APP_RSTRNT_API_URL: ${{ secrets.REACT_APP_RSTRNT_API_URL }}

jobs:

  lint: #ジョブ名
    runs-on: ubuntu-latest #実行環境(Ubuntuの最新版環境で実行)
    steps: #実行処理やコマンドを記述(上からnameの内容が実行される)
      - name: Git checkout current branch #作業ブランチにchekout
        uses: actions/checkout@v2 #サードパーティの公開アクションを利用
        with:
          ref: ${{ github.ref }}
      - name: Build docker image
        run: docker build -t $DOCKER_IMAGE_NAME -f ./Dockerfile.deploy .
      - name: Run lint in docker container
        run: docker run -t $DOCKER_IMAGE_NAME /bin/sh -c "yarn eslint . --ext .tsx --ext .ts"
      # -----------------------------------　slackへ通知 ----------------------------------------------------------------
      - name: Slack Notification on Success # テスト成功時はこちらのステップが実行される
        if: success()
        uses: rtCamp/action-slack-notify@v2.0.2
        env:
          SLACK_CHANNEL: ci
          SLACK_TITLE: Lint Success(CI)
          SLACK_COLOR: good
      - name: Slack Notification on Failure # テスト失敗時はこちらのステップが実行される
        uses: rtCamp/action-slack-notify@v2.0.2
        if: failure()
        env:
          SLACK_CHANNEL: ci
          SLACK_TITLE: Lint Failure(CI)
          SLACK_COLOR: danger

  test:
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - name: Git checkout current branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Build docker image
        run: docker build -t $DOCKER_IMAGE_NAME -f ./Dockerfile.deploy .
      - name: Run test in docker container
        run: docker run -t --env CI=true $DOCKER_IMAGE_NAME /bin/sh -c "yarn test"
      # -----------------------------------　slackへ通知 ----------------------------------------------------------------
      - name: Slack Notification on Success # テスト成功時はこちらのステップが実行される
        if: success()
        uses: rtCamp/action-slack-notify@v2.0.2
        env:
          SLACK_CHANNEL: ci
          SLACK_TITLE: Test Success(CI)
          SLACK_COLOR: good
      - name: Slack Notification on Failure # テスト失敗時はこちらのステップが実行される
        uses: rtCamp/action-slack-notify@v2.0.2
        if: failure()
        env:
          SLACK_CHANNEL: ci
          SLACK_TITLE: Test Failure(CI)
          SLACK_COLOR: danger

  push_docker_image:
    if: contains( github.ref, 'release') #developブランチにpushされたときに実行する
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - name: Git checkout current branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Build docker image
        run: |
          sed -e "s|__API_USER__|${REACT_APP_RSTRNT_API_USER}|g" -e "s|__API_PASS__|${REACT_APP_RSTRNT_API_PASSWORD}|g" -e "s|__RESTRANT_API_URL__|${REACT_APP_RSTRNT_API_URL}|g" ./src/edar/.env.example > ./src/edar/.env
          docker build -t $DEPLOY_DOCKER_IMAGE_NAME -f ./Dockerfile.deploy . --build-arg FIREBASE_PROJECT_ID=$FIREBASE_STAGING_PROJECT_ID
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: Push Docker image to GitHub Container Registry
        run: |
            IMAGE_TAG=$(echo ${{ github.ref }} | sed -e "s#refs/heads/release/v##g") 
            docker tag $DEPLOY_DOCKER_IMAGE_NAME ghcr.io/${{ github.repository_owner }}/edar:$IMAGE_TAG
            docker push ghcr.io/${{ github.repository_owner }}/edar:$IMAGE_TAG
      # -----------------------------------　slackへ通知 ----------------------------------------------------------------
      - name: Slack Notification on Success # テスト成功時はこちらのステップが実行される
        if: success()
        uses: rtCamp/action-slack-notify@v2.0.2
        env:
          SLACK_CHANNEL: ci
          SLACK_TITLE: Push Docker image to GitHub Container Registry Deploy Success(CI)
          SLACK_COLOR: good
      - name: Slack Notification on Failure # テスト失敗時はこちらのステップが実行される
        uses: rtCamp/action-slack-notify@v2.0.2
        if: failure()
        env:
          SLACK_CHANNEL: ci
          SLACK_TITLE: Push Docker image to GitHub Container Registry Deploy Failure(CI)
          SLACK_COLOR: danger

  staging_deploy:
    if: contains( github.ref, 'release') #releaseブランチにpushされたときに実行する
    runs-on: ubuntu-latest
    needs: [lint, test]
    env: 
      FIREBASE_STAGING_TOKEN: ${{ secrets.FIREBASE_STAGING_TOKEN }}
      FIREBASE_STAGING_API_KEY: ${{ secrets.FIREBASE_STG_API_KEY }}
      FIREBASE_STAGING_AUTH_DOMAIN: ${{ secrets.FIREBASE_STAGING_AUTH_DOMAIN }}
      FIREBASE_STAGING_PROJECT_ID: ${{ secrets.FIREBASE_STAGING_PROJECT_ID }}
      FIREBASE_STAGING_STORAGE_BUCKET: ${{ secrets.FIREBASE_STAGING_STORAGE_BUCKET }}
      FIREBASE_STAGING_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_STAGING_MESSAGING_SENDER_ID }}
      FIREBASE_STAGING_APP_ID: ${{ secrets.FIREBASE_STAGING_APP_ID }}
      FIREBASE_STAGING_MEASUREMENT_ID: ${{ secrets.FIREBASE_STAGING_MEASUREMENT_ID }}
    steps:
      - name: Git checkout current branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Build docker image
        run: |
          sed -e "s|__API_USER__|${REACT_APP_RSTRNT_API_USER}|g" -e "s|__API_PASS__|${REACT_APP_RSTRNT_API_PASSWORD}|g" -e "s|__RESTRANT_API_URL__|${REACT_APP_RSTRNT_API_URL}|g" -e "s|__FIREBASE_API_KEY__|${FIREBASE_STAGING_API_KEY}|g" -e "s|__FIREBASE_AUTH_DOMAIN__|${FIREBASE_STAGING_AUTH_DOMAIN}|g" -e "s|__FIREBASE_PROJECT_ID__|${FIREBASE_STAGING_PROJECT_ID}|g" -e "s|__FIREBASE_STORAGE_BUCKET__|${FIREBASE_STAGING_STORAGE_BUCKET}|g" -e "s|__FIREBASE_MESSAGING_SENDER_ID__|${FIREBASE_STAGING_MESSAGING_SENDER_ID}|g" -e "s|__FIREBASE_APP_ID__|${FIREBASE_STAGING_APP_ID}|g" -e "s|__FIREBASE_MEASUREMENT_ID__|${FIREBASE_STAGING_MEASUREMENT_ID}|g" ./src/edar/.env.example > ./src/edar/.env
          docker build -t $DEPLOY_DOCKER_IMAGE_NAME -f ./Dockerfile.deploy . --build-arg STAGE="CD" --build-arg FIREBASE_PROJECT_ID=$FIREBASE_STAGING_PROJECT_ID
      - name: Run staging deploy in docker container
        run: docker run -t --env CI=true --entrypoint=sh $DEPLOY_DOCKER_IMAGE_NAME -c "yarn build && yarn firebase deploy --token ${FIREBASE_STAGING_TOKEN}"
      # -----------------------------------　slackへ通知 ----------------------------------------------------------------
      - name: Slack Notification on Success # テスト成功時はこちらのステップが実行される
        if: success()
        uses: rtCamp/action-slack-notify@v2.0.2
        env:
          SLACK_CHANNEL: ci
          SLACK_TITLE: Staging Deploy Success(CD)
          SLACK_COLOR: good
      - name: Slack Notification on Failure # テスト失敗時はこちらのステップが実行される
        uses: rtCamp/action-slack-notify@v2.0.2
        if: failure()
        env:
          SLACK_CHANNEL: ci
          SLACK_TITLE: Staging Deploy Failure(CD)
          SLACK_COLOR: danger

  deploy:
    if: contains( github.ref, 'main') #mainブランチにpushされたときに実行する
    runs-on: ubuntu-latest
    needs: [lint, test]
    env: 
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
      FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
      FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
      FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
      FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
      FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
      FIREBASE_MEASUREMENT_ID: ${{ secrets.FIREBASE_MEASUREMENT_ID }}
    steps:
      - name: Git checkout current branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Build docker image
        run: |
          sed -e "s|___API_USER__|${REACT_APP_RSTRNT_API_USER}|g" -e "s|__API_PASS__|${REACT_APP_RSTRNT_API_PASSWORD}|g" -e "s|__RESTRANT_API_URL__|${REACT_APP_RSTRNT_API_URL}|g" -e "s|__FIREBASE_API_KEY__|${FIREBASE_API_KEY}|g" -e "s|__FIREBASE_AUTH_DOMAIN__|${FIREBASE_AUTH_DOMAIN}|g" -e "s|__FIREBASE_PROJECT_ID__|${FIREBASE_PROJECT_ID}|g"  -e "s|__FIREBASE_STORAGE_BUCKET__|${FIREBASE_STORAGE_BUCKET}|g" -e "s|__FIREBASE_MESSAGING_SENDER_ID__|${FIREBASE_MESSAGING_SENDER_ID}|g" -e "s|__FIREBASE_APP_ID__|${FIREBASE_APP_ID}|g" -e "s|__FIREBASE_MEASUREMENT_ID__|${FIREBASE_MEASUREMENT_ID}|g" ./src/edar/.env.example > ./src/edar/.env
          docker build -t $DEPLOY_DOCKER_IMAGE_NAME -f ./Dockerfile.deploy . --build-arg STAGE="CD" --build-arg FIREBASE_PROJECT_ID=$FIREBASE_PROJECT_ID
      - name: Run deploy in docker container
        run: docker run -t --env CI=true --entrypoint=sh $DEPLOY_DOCKER_IMAGE_NAME -c "yarn build && yarn firebase deploy --token ${FIREBASE_TOKEN}"
      # -----------------------------------　slackへ通知 ----------------------------------------------------------------
      - name: Slack Notification on Success # テスト成功時はこちらのステップが実行される
        if: success()
        uses: rtCamp/action-slack-notify@v2.0.2
        env:
          SLACK_CHANNEL: ci
          SLACK_TITLE: Deploy Success(CD)
          SLACK_COLOR: good
      - name: Slack Notification on Failure # テスト失敗時はこちらのステップが実行される
        uses: rtCamp/action-slack-notify@v2.0.2
        if: failure()
        env:
          SLACK_CHANNEL: ci
          SLACK_TITLE: Deploy Failure(CD)
          SLACK_COLOR: danger