name: EDAR CI CD 

on: push

env: # global環境変数を設定
  DOCKER_IMAGE_NAME: edar_react_test
  # DOCKER_FILE_NAME:
  DEPLOY_DOCKER_IMAGE_NAME: edar_deploy
  SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
  REACT_APP_RSTRNT_API_USER: ${{ secrets.REACT_APP_RSTRNT_API_USER }}
  REACT_APP_RSTRNT_API_PASSWORD: ${{ secrets.REACT_APP_RSTRNT_API_PASSWORD }}
  REACT_APP_RSTRNT_API_URL: ${{ secrets.REACT_APP_RSTRNT_API_URL }}

jobs:
  test:
      runs-on: ubuntu-latest
      needs: [lint]
      steps:
        - name: Git checkout current branch
          uses: actions/checkout@v2
          with:
            ref: ${{ github.ref }}
        - name: Build docker image
          run: docker build -t $DOCKER_IMAGE_NAME -f ./Dockerfile.deploy .
        - name: Run test in docker container
          run: docker run -t --env CI=true $DOCKER_IMAGE_NAME /bin/sh -c "yarn test"
        # -----------------------------------　slackへ通知 ----------------------------------------------------------------
        - name: Slack Notification on Success # テスト成功時はこちらのステップが実行される
          if: success()
          uses: rtCamp/action-slack-notify@v2.0.2
          env:
            SLACK_CHANNEL: ci
            SLACK_TITLE: Test Success(CI)
            SLACK_COLOR: good
        - name: Slack Notification on Failure # テスト失敗時はこちらのステップが実行される
          uses: rtCamp/action-slack-notify@v2.0.2
          if: failure()
          env:
            SLACK_CHANNEL: ci
            SLACK_TITLE: Test Failure(CI)
            SLACK_COLOR: danger